"""empty message

Revision ID: 2d05dd592e32
Revises: ef97797e9be6
Create Date: 2023-02-07 02:53:15.423421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d05dd592e32'
down_revision = 'ef97797e9be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('purchased', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('carts', 'purchased')
    # ### end Alembic commands ###
